### ISSUE TITLE
Is there any way to retrieve the visibility state with dbus?

### ISSUE THREAD

**Issue by mgtitimoli** [panzi/Yakuake#2]
Hi @panzi,

Sorry for opening an issue here, but I landed in your repo after had searched for a long time about the possibility to get the visibility state of yakuake window using dbus from the command line (qdbus), and maybe you can give me some hint of how to do it.

I have seen that **MainApplication** inherits from **QWidget** and this last one has a method **isVisible**, but I can't find a way to invoke it or get the value of any property from where I can get this information. Do you know if there is a way to obtain the visibility state of the window?

Thanks!!

**Comment by panzi** [comment]
Sorry, no idea. I just hacked into the "open tab in current directory" feature. Haven't looked at any code that doesn't concern that feature.
