### ISSUE TITLE
about full screen mode

### ISSUE THREAD

**Issue by hwpplayer1** [panzi/Yakuake#3]
`hwpplayer1@hwpplayer1-Aspire-V3-772G:~$ lsb_release -da
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial`

I use it. When i make it full screen and then exit the terminal and open Yakuake terminal again , it still is full screen. So i need it to be fixed size which decided on height settings.

**Comment by panzi** [comment]
This is only a fork of Yakuake where I fixed a small thing. I'm not the maintainer of Yakuake, please submit bugs or feature requests to the KDE bugtracker: https://bugs.kde.org/describecomponents.cgi?product=yakuake

**Comment by hwpplayer1** [comment]
Yes i talked with Sho and gave me the same link. Thanks
